---

- name: Install repos
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - epel-release
    - https://mirror.webtatic.com/yum/el7/webtatic-release.rpm

- name: Install packages
  yum:
    name: '{{ item }}'
  with_items:
    - policycoreutils-python
    - nginx
    - mariadb-server
    - MySQL-python
    - php71w-fpm
    - php71w-gd
    - php71w-xml
    - php71w-xmlrpc
    - php71w-opcache
    - php71w-soap
    - php71w-mbstring 
    - php71w-intl
    - php71w-mysql
    - php71w-cli
    
- name: Copy nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: Nginx restart

- name: Copy my.cnf
  copy:
    src: "my.cnf.d/{{ item }}"
    dest: /etc/my.cnf.d/
  with_items:
    - client.cnf
    - mysql-clients.cnf
    - server.cnf
  notify: MariaDB restart

- name: Copy php-fpm.d/www.conf
  copy:
    src: "php-fpm.d/www.conf"
    dest: "/etc/php-fpm.d/www.conf"
  notify: PHP-FPM restart

- name: Copy php.ini
  copy:
    src: "php.ini"
    dest: "/etc/php.ini"
  notify: PHP-FPM restart

- name: Enable and start services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - nginx
    - php-fpm
    - mariadb

- name: Create session directory
  file:
    path: /var/lib/php/session
    state: directory
    owner: apache
    group: apache

